export const AirpondsData = [
  {
    id: 1,
    image: "/airponds/airpond1.webp",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "399",
    pastPrice: "799",
    offer: "65% off",
    color: "black",
    name: "Airbords",
  },
  {
    id: 2,
    image: "/airponds/airpond2.webp",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "599",
    pastPrice: "899",
    offer: "65% off",
    color: "red",
    name: "Airbords",
  },
  {
    id: 3,
    image: "/airponds/airpond3.webp",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "899",
    pastPrice: "1299",
    offer: "65% off",
    color: "green",
    name: "Airbords",
  },
  {
    id: 4,
    image: "/airponds/airpond4.webp",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "1299",
    pastPrice: "1599",
    offer: "65% off",
    color: "blue",
    name: "Airbords",
  },
  {
    id: 5,
    image: "/airponds/airpond5.webp",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "599",
    pastPrice: "999",
    offer: "65% off",
    color: "black",
    name: "Airbords",
  },
  {
    id: 6,
    image: "/airponds/airpond6.webp",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "1399",
    pastPrice: "1599",
    offer: "65% off",
    color: "green",
    name: "Airbords",
  },
  {
    id: 7,
    image: "/airponds/airpond7.webp",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "459",
    pastPrice: "799",
    offer: "65% off",
    color: "blue",
    name: "Airbords",
  },
  {
    id: 8,
    image: "/airponds/airpond8.png",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "679",
    pastPrice: "999",
    offer: "65% off",
    color: "red",
    name: "Airbords",
  },
  {
    id: 9,
    image: "/airponds/airpond9.jpg",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "1,599",
    pastPrice: "1,999",
    offer: "65% off",
    color: "black",
    name: "Airbords",
  },
  {
    id: 10,
    image: "/airponds/airpond10.webp",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "349",
    pastPrice: "599",
    offer: "65% off",
    color: "blue",
    name: "Airbords",
  },
  {
    id: 11,
    image: "/airponds/airpond11.webp",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "1,799",
    pastPrice: "1,999",
    offer: "65% off",
    color: "red",
    name: "Airbords",
  },
  {
    id: 12,
    image: "/airponds/airpond12.jpg",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "1,399",
    pastPrice: "1,599",
    offer: "65% off",
    color: "green",
    name: "Airbords",
  },
  {
    id: 13,
    image: "/airponds/airpond13.png",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "1,899",
    pastPrice: "2,499",
    offer: "65% off",
    color: "red",
    name: "Airbords",
  },
  {
    id: 14,
    image: "/airponds/airpond14.png",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "1,699",
    pastPrice: "1,899",
    offer: "65% off",
    color: "red",
    name: "Airbords",
  },
  {
    id: 15,
    image: "/airponds/airpond15.jpg",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "1,199",
    pastPrice: "1,399",
    offer: "65% off",
    color: "black",
    name: "Airbords",
  },
  {
    id: 16,
    image: "/airponds/airpond16.jpg",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "499",
    pastPrice: "999",
    offer: "65% off",
    color: "red",
    name: "Airbords",
  },
  {
    id: 17,
    image: "/airponds/airpond17.jpg",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "1,499",
    pastPrice: "1,799",
    offer: "65% off",
    color: "green",
    name: "Airbords",
  },
  {
    id: 18,
    image: "/airponds/airpond18.webp",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "899",
    pastPrice: "1,299",
    offer: "65% off",
    color: "red",
    name: "Airbords",
  },
  {
    id: 19,
    image: "/airponds/airpond19.jpg",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "1,299",
    pastPrice: "1,499",
    offer: "65% off",
    color: "blue",
    name: "Airbords",
  },
  {
    id: 20,
    image: "/airponds/airpond20.jpg",
    company: "Airponds",
    description: "Airponds 131 with upto 60 hours",
    price: "759",
    pastPrice: "999",
    offer: "65% off",
    color: "red",
    name: "Airbords",
  },
];
