export const Ladies = [
  {
    id: 1,
    image: "/womenDresses/wmImage1.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "499",
    postPrice: "999",
    offer: "71% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 2,
    image: "/womenDresses/wmImage2.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "345",
    postPrice: "1299",
    offer: "56% off",
    color: "green",
    name: "Women dress",
  },
  {
    id: 3,
    image: "/womenDresses/wmImage3.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "599",
    postPrice: "1599",
    offer: "72% off",
    color: "white",
    name: "Women dress",
  },
  {
    id: 4,
    image: "/womenDresses/wmImage4.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "699",
    postPrice: "1299",
    offer: "76% off",
    color: "blue",
    name: "Women dress",
  },
  {
    id: 5,
    image: "/womenDresses/wmImage5.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1299",
    postPrice: "2999",
    offer: "89% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 6,
    image: "/womenDresses/wmImage6.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1799",
    postPrice: "3999",
    offer: "82% off",
    color: "green",
    name: "Women dress",
  },
  {
    id: 7,
    image: "/womenDresses/wmImage7.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1599",
    postPrice: "2999",
    offer: "56% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 8,
    image: "/womenDresses/wmImage8.jpeg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "759",
    postPrice: "1999",
    offer: "72% off",
    color: "white",
    name: "Women dress",
  },
  {
    id: 9,
    image: "/womenDresses/wmImage9.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "399",
    postPrice: "999",
    offer: "56% off",
    color: "green",
    name: "Women dress",
  },
  {
    id: 10,
    image: "/womenDresses/wmImage10.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1299",
    postPrice: "1999",
    offer: "82% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 11,
    image: "/womenDresses/wmImage11.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "199",
    postPrice: "599",
    offer: "45% off",
    color: "blue",
    name: "Women dress",
  },
  {
    id: 12,
    image: "/womenDresses/wmImage12.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "299",
    postPrice: "599",
    offer: "48% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 13,
    image: "/womenDresses/wmImage13.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "459",
    postPrice: "1999",
    offer: "56% off",
    color: "geen",
    name: "Women dress",
  },
  {
    id: 14,
    image: "/womenDresses/wmImage14.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1199",
    postPrice: "1999",
    offer: "75% off",
    color: "white",
    name: "Women dress",
  },
  {
    id: 15,
    image: "/womenDresses/wmImage15.jpeg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1599",
    postPrice: "2999",
    offer: "75% off",
    color: "green",
    name: "Women dress",
  },
  {
    id: 16,
    image: "/womenDresses/wmImage16.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1299",
    postPrice: "2999",
    offer: "75% off",
    color: "blue",
    name: "Women dress",
  },
  {
    id: 17,
    image: "/womenDresses/wmImage17.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1599",
    postPrice: "2999",
    offer: "76% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 18,
    image: "/womenDresses/wmImage18.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "459",
    postPrice: "999",
    offer: "45% off",
    color: "blue",
    name: "Women dress",
  },
  {
    id: 19,
    image: "/womenDresses/wmImage19.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "678",
    postPrice: "999",
    offer: "54% off",
    color: "green",
    name: "Women dress",
  },
  {
    id: 20,
    image: "/womenDresses/wmImage20.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1999",
    postPrice: "2999",
    offer: "86% off",
    color: "white",
    name: "Women dress",
  },
  {
    id: 21,
    image: "/womenDresses/wmImage21.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "599",
    postPrice: "1499",
    offer: "75% off",
    color: "blue",
    name: "Women dress",
  },
  {
    id: 22,
    image: "/womenDresses/wmImage22.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "899",
    postPrice: "999",
    offer: "86% off",
    color: "blue",
    name: "Women dress",
  },

  {
    id: 23,
    image: "/womenDresses/wmImage23.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "459",
    postPrice: "1499",
    offer: "66% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 24,
    image: "/womenDresses/wmImage24.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1999",
    postPrice: "2999",
    offer: "86% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 25,
    image: "/womenDresses/wmImage25.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "499",
    postPrice: "1999",
    offer: "45% off",
    color: "white",
    name: "Women dress",
  },
  {
    id: 26,
    image: "/womenDresses/wmImage26.jpeg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1999",
    postPrice: "2999",
    offer: "86% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 27,
    image: "/womenDresses/wmImage27.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "599",
    postPrice: "1999",
    offer: "56% off",
    color: "green",
    name: "Women dress",
  },
  {
    id: 28,
    image: "/womenDresses/wmImage28.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "699",
    postPrice: "1999",
    offer: "67% off",
    color: "blue",
    name: "Women dress",
  },
  {
    id: 29,
    image: "/womenDresses/wmImage29.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "345",
    postPrice: "999",
    offer: "62% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 30,
    image: "/womenDresses/wmImage30.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "999",
    postPrice: "1999",
    offer: "76% off",
    color: "green",
    name: "Women dress",
  },
  {
    id: 31,
    image: "/womenDresses/wmImage31.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "799",
    postPrice: "1999",
    offer: "56% off",
    color: "blue",
    name: "Women dress",
  },
  {
    id: 32,
    image: "/womenDresses/wmImage32.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "599",
    postPrice: "1999",
    offer: "86% off",
    color: "white",
    name: "Women dress",
  },
  {
    id: 33,
    image: "/womenDresses/wmImage33.avif",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "679",
    postPrice: "1999",
    offer: "56% off",
    color: "green",
    name: "Women dress",
  },
  {
    id: 34,
    image: "/womenDresses/wmImage34.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "499",
    postPrice: "999",
    offer: "56% off",
    color: "red",
    name: "Women dress",
  },
  {
    id: 35,
    image: "/womenDresses/wmImage35.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "599",
    postPrice: "1999",
    offer: "72% off",
    color: "white",
    name: "Women dress",
  },
  {
    id: 36,
    image: "/womenDresses/wmImage36.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "349",
    postPrice: "999",
    offer: "56% off",
    color: "blue",
    name: "Women dress",
  },
  {
    id: 37,
    image: "/womenDresses/wmImage37.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "599",
    postPrice: "1999",
    offer: "86% off",
    color: "white",
    name: "Women dress",
  },
  {
    id: 38,
    image: "/womenDresses/wmImage38.webp",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1399",
    postPrice: "1999",
    offer: "76% off",
    color: "blue",
    name: "Women dress",
  },
  {
    id: 39,
    image: "/womenDresses/wmImage39.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "599",
    postPrice: "1999",
    offer: "86% off",
    color: "green",
    name: "Women dress",
  },
  {
    id: 40,
    image: "/womenDresses/wmImage40.jpg",
    company: "VEBNOR",
    description: "Girls Regular Fit",
    price: "1599",
    postPrice: "2999",
    offer: "82% off",
    color: "green",
    name: "Women dress",
  },
];
