export const Gents = [
  {
    id: 1,
    image: "/DummyImages/Image1.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "288",
    pastPrice: "999",
    offer: "71% off",
    name: "Men Shirts",
  },
  {
    id: 2,
    image: "/DummyImages/Image2.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "599",
    pastPrice: "1299",
    offer: "76% off",
    name: "Men Shirts",
  },
  {
    id: 3,
    image: "/DummyImages/Image3.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "658",
    pastPrice: "1599",
    offer: "68% off",
    name: "Men Shirts",
  },
  {
    id: 4,

    image: "/DummyImages/Image4.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "1259",
    pastPrice: "1999",
    offer: "86% off",
    name: "Men Shirts",
  },
  {
    id: 5,

    image: "/DummyImages/Image5.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "758",
    pastPrice: "1499",
    offer: "62% off",
    name: "Men Shirts",
  },
  {
    id: 6,

    image: "/DummyImages/Image6.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "398",
    pastPrice: "999",
    offer: "75% off",
    name: "Men Shirts",
  },
  {
    id: 7,

    image: "/DummyImages/Image7.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "258",
    pastPrice: "699",
    offer: "58% off",
    name: "Men Shirts",
  },
  {
    id: 8,

    image: "/DummyImages/Image8.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "1899",
    pastPrice: "2999",
    offer: "76% off",
    name: "Men Shirts",
  },
  {
    id: 9,

    image: "/DummyImages/Image9.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "498",
    pastPrice: "999",
    offer: "71% off",
    name: "Men Shirts",
  },
  {
    id: 10,

    image: "/DummyImages/Image10.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "899",
    pastPrice: "1699",
    offer: "82% off",
    name: "Men Shirts",
  },
  {
    id: 11,

    image: "/DummyImages/Image11.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "568",
    pastPrice: "999",
    offer: "71% off",
    name: "Men Shirts",
  },
  {
    id: 12,

    image: "/DummyImages/Image12.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "788",
    postPrice: "1299",
    offer: "72% off",
    name: "Men Shirts",
  },
  {
    id: 13,

    image: "/DummyImages/Image13.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "759",
    pastPrice: "1299",
    offer: "65% off",
    name: "Men Shirts",
  },
  {
    id: 14,

    image: "/DummyImages/Image14.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "958",
    pastPrice: "1499",
    offer: "56% off",
    name: "Men Shirts",
  },
  {
    id: 15,

    image: "/DummyImages/Image15.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "458",
    pastPrice: "999",
    offer: "54% off",
    name: "Men Shirts",
  },
  {
    id: 16,

    image: "/DummyImages/Image16.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "899",
    pastPrice: "1299",
    offer: "74% off",
    name: "Men Shirts",
  },
  {
    id: 17,

    image: "/DummyImages/Image17.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "1599",
    pastPrice: "2999",
    offer: "82% off",
    name: "Men Shirts",
  },
  {
    id: 18,

    image: "/DummyImages/Image18.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "1789",
    pastPrice: "1289",
    offer: "72% off",
    name: "Men Shirts",
  },
  {
    id: 19,

    image: "/DummyImages/Image19.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "989",
    pastPrice: "1299",

    offer: "71% off",
    name: "Men Shirts",
  },
  {
    id: 20,

    image: "/DummyImages/Image20.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "1399",
    pastPrice: "2599",
    offer: "86% off",
    name: "Men Shirts",
  },
  {
    id: 21,

    image: "/DummyImages/Image21.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "1158",
    pastPrice: "1999",
    offer: "74% off",
    name: "Men Shirts",
  },
  {
    id: 22,

    image: "/DummyImages/Image22.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "299",
    pastPrice: "999",
    offer: "71% off",
    name: "Men Shirts",
  },
  {
    id: 23,

    image: "/DummyImages/Image23.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "568",
    pastPrice: "999",
    offer: "54% off",
    name: "Men Shirts",
  },
  {
    id: 24,

    image: "/DummyImages/Image24.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "288",
    pastPrice: "999",
    offer: "71% off",
    name: "Men Shirts",
  },
  {
    id: 25,

    image: "/DummyImages/Image25.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "768",
    pastPrice: "1499",
    offer: "56% off",
    name: "Men Shirts",
  },
  {
    id: 26,

    image: "/DummyImages/Image26.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "1258",
    pastPrice: "1999",
    offer: "71% off",
    name: "Men Shirts",
  },
  {
    id: 27,

    image: "/DummyImages/Image27.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "1799",
    pastPrice: "2299",
    offer: "72% off",
    name: "Men Shirts",
  },
  {
    id: 28,
    image: "/DummyImages/Image28.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "1698",
    pastPrice: "1999",
    offer: "71% off",
    name: "Men Shirts",
  },
  {
    id: 29,

    image: "/DummyImages/image29.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "1298",
    pastPrice: "1999",
    offer: "78% off",
    name: "Men Shirts",
  },
  {
    id: 30,

    image: "/DummyImages/image30.webp",
    company: "VEBNOR",
    description: "Men Regular Fit",
    price: "778",
    pastPrice: "999",
    offer: "56% off",
    name: "Men Shirts",
  },
];
