export const iPhones = [
  {
    id: 1,
    image: "/iphones/iphone1.jpg",
    internal: "256 GB",
    price: "75,999",
    company: "Apple",
    color: "black",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 2,
    image: "/iphones/iphone2.jpg",
    internal: "128 GB",
    price: "45,999",
    company: "Apple",
    color: "black",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 3,
    image: "/iphones/iphone3.jpg",
    internal: "128 GB",
    price: "72,999",
    company: "Apple",
    color: "white",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 4,
    image: "/iphones/iphone4.jpg",
    internal: "128 GB",
    price: "89,999",
    company: "Apple",
    color: "green",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 5,
    image: "/iphones/iphone5.jpg",
    internal: "128 GB",
    price: "93,999",
    company: "Apple",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 6,
    image: "/iphones/iphone6.jpg",
    internal: "128 GB",
    price: "96,999",
    company: "Apple",
    color: "black",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 7,
    image: "/iphones/iphone7.jpg",
    internal: "128 GB",
    price: "80,999",
    company: "Apple",
    color: "red",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 8,
    image: "/iphones/iphone8.jpg",
    internal: "128 GB",
    price: "63,999",
    company: "Apple",
    color: "white",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 9,
    image: "/iphones/iphone9.jpg",
    internal: "128 GB",
    price: "55,999",
    company: "Apple",
    color: "green",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 10,
    image: "/iphones/iphone10.jpg",
    internal: "128 GB",
    price: "55,999",
    company: "Apple",
    color: "white",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 11,
    image: "/iphones/iphone11.jpg",
    internal: "128 GB",
    price: "69,999",
    company: "Apple",
    color: "black",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 12,
    image: "/iphones/iphone12.jpg",
    internal: "128 GB",
    price: "49,999",
    company: "Apple",
    color: "red",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 13,
    image: "/iphones/iphone13.jpg",
    internal: "128 GB",
    price: "80,999",
    company: "Apple",
    color: "green",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 14,
    image: "/iphones/iphone14.jpg",
    internal: "128 GB",
    price: "56,999",
    company: "Apple",
    color: "white",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 15,
    image: "/iphones/iphone15.jpg",
    internal: "128 GB",
    price: "95,999",
    company: "Apple",
    color: "black",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 16,
    image: "/iphones/iphone16.jpg",
    internal: "128 GB",
    price: "85,999",
    company: "Apple",
    color: "red",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 17,
    image: "/iphones/iphone17.jpg",
    internal: "128 GB",
    price: "45,999",
    company: "Apple",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 18,
    image: "/iphones/iphone15.jpg",
    internal: "128 GB",
    price: "79,999",
    company: "Apple",
    color: "green",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 19,
    image: "/iphones/iphone19.webp",
    internal: "128 GB",
    price: "35,999",
    company: "Apple",
    color: "black",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 20,
    image: "/iphones/iphone20.jpg",
    internal: "128 GB",
    price: "48,999",
    company: "Apple",
    color: "red",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 21,
    image: "/iphones/iphone21.jpg",
    internal: "128 GB",
    price: "95,999",
    company: "Apple",
    color: "black",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 22,
    image: "/iphones/iphone22.webp",
    internal: "128 GB",
    price: "99,999",
    company: "Apple",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 23,
    image: "/iphones/iphone31.jpg",
    internal: "128 GB",
    price: "95,999",
    company: "Apple",
    color: "red",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 24,
    image: "/iphones/iphone24.jpg",
    internal: "128 GB",
    price: "49,999",
    company: "Apple",
    color: "white",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 25,
    image: "/iphones/iphone25.jpg",
    internal: "128 GB",
    price: "79,999",
    company: "Apple",
    color: "black",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 26,
    image: "/iphones/iphone26.webp",
    internal: "128 GB",
    price: "84,999",
    company: "Apple",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 27,
    image: "/iphones/iphone27.webp",
    internal: "128 GB",
    price: "49,999",
    company: "Apple",
    color: "red",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 28,
    image: "/iphones/iphone28.jpg",
    internal: "128 GB",
    price: "99,999",
    company: "Apple",
    color: "black",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 29,
    image: "/iphones/iphone29.jpg",
    internal: "128 GB",
    price: "69,999",
    company: "Apple",
    color: "white",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
  {
    id: 30,
    image: "/iphones/iphone30.jpg",
    internal: "128 GB",
    price: "59,999",
    company: "Apple",
    color: "green",
    description: "1 year warrenty for phone",
    name: "Iphones",
  },
];
