export const LadiesSarees = [
  {
    id: 1,
    image: "/womenSarees/wmsImages1.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "599",
    postPrice: "999",
    offer: "76% off",
    color: "red",
    name: "Sarees",
  },
  {
    id: 2,
    image: "/womenSarees/wmsImages2.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "799",
    postPrice: "1299",
    offer: "71% off",
    color: "blue",
    name: "Sarees",
  },
  {
    id: 3,
    image: "/womenSarees/wmsImage3.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1299",
    postPrice: "1999",
    offer: "56% off",
    color: "white",
    name: "Sarees",
  },
  {
    id: 4,
    image: "/womenSarees/wmsImage4.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "459",
    postPrice: "999",
    offer: "56% off",
    color: "green",
    name: "Sarees",
  },
  {
    id: 5,
    image: "/womenSarees/wmsImage5.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1899",
    postPrice: "2999",
    offer: "76% off",
    color: "white",
    name: "Sarees",
  },
  {
    id: 6,
    image: "/womenSarees/wmsImage6.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1389",
    postPrice: "1999",
    offer: "76% off",
    color: "white",
    name: "Sarees",
  },
  {
    id: 7,
    image: "/womenSarees/wmsImage7.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1599",
    postPrice: "2999",
    offer: "76% off",
    color: "blue",
    name: "Sarees",
  },
  {
    id: 8,
    image: "/womenSarees/wmsImage8.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "999",
    postPrice: "1599",
    offer: "56% off",
    color: "green",
    name: "Sarees",
  },
  {
    id: 9,
    image: "/womenSarees/wmsImage9.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "359",
    postPrice: "1599",
    offer: "56% off",
    color: "red",
    name: "Sarees",
  },
  {
    id: 10,
    image: "/womenSarees/wmsImage10.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "969",
    postPrice: "1999",
    offer: "76% off",
    color: "red",
    name: "Sarees",
  },
  {
    id: 11,
    image: "/womenSarees/wmsImage11.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "599",
    postPrice: "999",
    offer: "76% off",
    color: "white",
    name: "Sarees",
  },
  {
    id: 12,
    image: "/womenSarees/wmsImage12.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1599",
    postPrice: "1999",
    offer: "56% off",
    color: "green",
    name: "Sarees",
  },
  {
    id: 13,
    image: "/womenSarees/wmsImage13.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "699",
    postPrice: "1999",
    offer: "78% off",
    color: "red",
    name: "Sarees",
  },
  {
    id: 14,
    image: "/womenSarees/wmsImage14.jpeg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "599",
    postPrice: "999",
    offer: "76% off",
    color: "white",
    name: "Sarees",
  },
  {
    id: 15,
    image: "/womenSarees/wmsImage15.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "769",
    postPrice: "1999",
    offer: "66% off",
    color: "red",
    name: "Sarees",
  },
  {
    id: 16,
    image: "/womenSarees/wmsImage16.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "459",
    postPrice: "1999",
    offer: "76% off",
    color: "green",
    name: "Sarees",
  },
  {
    id: 17,
    image: "/womenSarees/wmsImage17.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1699",
    postPrice: "2999",
    offer: "72% off",
    color: "white",
    name: "Sarees",
  },
  {
    id: 18,
    image: "/womenSarees/wmsImage18.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1299",
    postPrice: "1999",
    offer: "68% off",
    color: "blue",
    name: "Sarees",
  },
  {
    id: 19,
    image: "/womenSarees/wmsImage19.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1699",
    postPrice: "1999",
    offer: "46% off",
    color: "red",
    name: "Sarees",
  },
  {
    id: 20,
    image: "/womenSarees/wmsImage20.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1399",
    postPrice: "1599",
    offer: "76% off",
    color: "blue",
    name: "Sarees",
  },
  {
    id: 21,
    image: "/womenSarees/wmsImage21.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1399",
    postPrice: "1999",
    offer: "67% off",
    color: "green",
    name: "Sarees",
  },
  {
    id: 22,
    image: "/womenSarees/wmsImage22.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1299",
    postPrice: "1999",
    offer: "56% off",
    color: "green",
    name: "Sarees",
  },
  {
    id: 23,
    image: "/womenSarees/wmsImage23.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "199",
    postPrice: "599",
    offer: "56% off",
    color: "blue",
    name: "Sarees",
  },
  {
    id: 23,
    image: "/womenSarees/wmsImage44.jpeg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "349",
    postPrice: "999",
    offer: "56% off",
    color: "black",
    name: "Sarees",
  },
  {
    id: 24,
    image: "/womenSarees/wmsImage46.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1499",
    postPrice: "1999",
    offer: "66% off",
    color: "white",
    name: "Sarees",
  },
  {
    id: 25,
    image: "/womenSarees/wmsImage43.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "679",
    postPrice: "1999",
    offer: "56% off",
    color: "blue",
    name: "Sarees",
  },
  {
    id: 26,
    image: "/womenSarees/wmsImage26.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1299",
    postPrice: "1999",
    offer: "56% off",
    color: "green",
    name: "Sarees",
  },
  {
    id: 27,
    image: "/womenSarees/wmsImage27.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1799",
    postPrice: "2999",
    offer: "86% off",
    color: "green",
    name: "Sarees",
  },
  {
    id: 28,
    image: "/womenSarees/wmsImage28.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "899",
    postPrice: "1999",
    offer: "56% off",
    color: "white",
    name: "Sarees",
  },
  {
    id: 29,
    image: "/womenSarees/wmsImage29.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1399",
    postPrice: "1999",
    offer: "56% off",
    color: "red",
    name: "Sarees",
  },
  {
    id: 30,
    image: "/womenSarees/wmsImage30.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "99",
    postPrice: "999",
    offer: "56% off",
    color: "green",
    name: "Sarees",
  },
  {
    id: 31,
    image: "/womenSarees/wmsImage31.webp",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "346",
    postPrice: "1999",
    offer: "56% off",
    color: "green",
    name: "Sarees",
  },
  {
    id: 32,
    image: "/womenSarees/wmsImage32.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "899",
    postPrice: "1599",
    offer: "76% off",
    color: "blue",
    name: "Sarees",
  },
  {
    id: 33,
    image: "/womenSarees/wmsImage33.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "499",
    postPrice: "999",
    offer: "56% off",
    color: "red",
    name: "Sarees",
  },
  {
    id: 34,
    image: "/womenSarees/wmsImage44.jpeg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1299",
    postPrice: "1999",
    offer: "56% off",
    color: "white",
    name: "Sarees",
  },
  {
    id: 35,
    image: "/womenSarees/wmsImage35.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "599",
    postPrice: "999",
    offer: "56% off",
    color: "red",
    name: "Sarees",
  },
  {
    id: 36,
    image: "/womenSarees/wmsImage36.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1799",
    postPrice: "2999",
    offer: "56% off",
    color: "blue",
    name: "Sarees",
  },
  {
    id: 37,
    image: "/womenSarees/wmsImage37.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1999",
    postPrice: "2999",
    offer: "56% off",
    color: "white",
    name: "Sarees",
  },
  {
    id: 38,
    image: "/womenSarees/wmsImage45.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "1199",
    postPrice: "1999",
    offer: "75% off",
    color: "red",
    name: "Sarees",
  },
  {
    id: 39,
    image: "/womenSarees/wmsImage39.jpg",
    company: "VEBNOR",
    description: "Ladies Regular sarees",
    price: "789",
    postPrice: "999",
    offer: "56% off",
    color: "green",
    name: "Sarees",
  },
];
