export const LaptopData = [
  {
    id: 1,
    image: "/laptops/laptop1.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "59,999",
    pastPrice: "62,999",
    offer: "76% off",
    color: "red",
    name: "Laptops",
  },
  {
    id: 2,
    image: "/laptops/laptop2.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "45,999",
    pastPrice: "46,999",
    offer: "76% off",
    color: "white",
    name: "Laptops",
  },
  {
    id: 3,
    image: "/laptops/laptop3.webp",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "34,999",
    pastPrice: "36,999",
    offer: "76% off",
    color: "black",
    name: "Laptops",
  },
  {
    id: 4,
    image: "/laptops/laptop4.webp",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "78,999",
    pastPrice: "82,999",
    offer: "76% off",
    color: "black",
    name: "Laptops",
  },
  {
    id: 5,
    image: "/laptops/laptop5.webp",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "67,999",
    pastPrice: "70,999",
    offer: "76% off",
    color: "blue",
    name: "Laptops",
  },
  {
    id: 6,
    image: "/laptops/laptop6.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "56,999",
    pastPrice: "60,999",
    offer: "76% off",
    color: "green",
    name: "Laptops",
  },
  {
    id: 7,
    image: "/laptops/laptop7.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "88,999",
    pastPrice: "90,999",
    offer: "76% off",
    color: "balck",
    name: "Laptops",
  },
  {
    id: 8,
    image: "/laptops/laptop8.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "34,999",
    pastPrice: "38,999",
    offer: "76% off",
    color: "white",
    name: "Laptops",
  },
  {
    id: 9,
    image: "/laptops/laptop9.png",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "29,999",
    pastPrice: "32,999",
    offer: "76% off",
    color: "green",
    name: "Laptops",
  },
  {
    id: 10,
    image: "/laptops/laptop10.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "89,999",
    pastPrice: "92,999",
    offer: "76% off",
    color: "red",
    name: "Laptops",
  },
  {
    id: 11,
    image: "/laptops/laptop11.webp",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "59,999",
    pastPrice: "62,999",
    offer: "76% off",
    color: "blue",
    name: "Laptops",
  },
  {
    id: 12,
    image: "/laptops/laptop12.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "34,999",
    pastPrice: "38,999",
    offer: "76% off",
    color: "white",
    name: "Laptops",
  },
  {
    id: 13,
    image: "/laptops/laptop13.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "92,999",
    pastPrice: "99,999",
    offer: "76% off",
    color: "red",
    name: "Laptops",
  },
  {
    id: 14,
    image: "/laptops/laptop14.png",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "65,999",
    pastPrice: "68,999",
    offer: "76% off",
    color: "black",
    name: "Laptops",
  },
  {
    id: 15,
    image: "/laptops/laptop15.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "75,999",
    pastPrice: "78,999",
    offer: "76% off",
    color: "blue",
    name: "Laptops",
  },
  {
    id: 16,
    image: "/laptops/laptop16.webp",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "45,999",
    pastPrice: "48,999",
    offer: "76% off",
    color: "green",
    name: "Laptops",
  },
  {
    id: 17,
    image: "/laptops/laptop17.webp",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "86,999",
    pastPrice: "88,999",
    offer: "76% off",
    color: "black",
    name: "Laptops",
  },
  {
    id: 18,
    image: "/laptops/laptop18.png",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "56,999",
    pastPrice: "58,999",
    offer: "76% off",
    color: "black",
    name: "Laptops",
  },
  {
    id: 19,
    image: "/laptops/laptop19.webp",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "87,999",
    pastPrice: "89,999",
    offer: "76% off",
    color: "red",
    name: "Laptops",
  },
  {
    id: 20,
    image: "/laptops/laptop20.avif",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "59,999",
    pastPrice: "62,999",
    offer: "76% off",
    color: "blue",
    name: "Laptops",
  },
  {
    id: 21,
    image: "/laptops/laptop21.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "89,999",
    pastPrice: "92,999",
    offer: "76% off",
    color: "red",
    name: "Laptops",
  },
  {
    id: 22,
    image: "/laptops/laptop22.png",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "34,999",
    pastPrice: "38,999",
    offer: "76% off",
    color: "blue",
    name: "Laptops",
  },
  {
    id: 23,
    image: "/laptops/laptop23.avif",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "87,999",
    pastPrice: "89,999",
    offer: "76% off",
    color: "green",
    name: "Laptops",
  },
  {
    id: 24,
    image: "/laptops/laptop24.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "65,999",
    pastPrice: "68,999",
    offer: "76% off",
    color: "red",
    name: "Laptops",
  },
  {
    id: 25,
    image: "/laptops/laptop25.jpg",
    company: "Laptop",
    description: "1 Year garrenty for Laptop",
    price: "78,999",
    pastPrice: "81,999",
    offer: "76% off",
    color: "blue",
    name: "Laptops",
  },
];
