export const OnePluses = [
  {
    id: 1,
    name: "onePlus",
    image: "/onePlus/oneplus1.webp",
    internal: "128 GB",
    price: `32,999`,
    company: "OnePlus",
    color: "red",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 2,
    name: "onePlus",
    image: "/onePlus/oneplus2.jpg",
    internal: "258 GB",
    price: "45,999",
    company: "OnePlus",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 3,
    name: "onePlus",
    image: "/onePlus/oneplus3.webp",
    internal: "258 GB",
    price: "54,999",
    company: "OnePlus",
    color: "green",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 4,
    name: "onePlus",
    image: "/onePlus/oneplus4.jpg",
    internal: "128 GB",
    price: "78,999",
    company: "OnePlus",
    color: "white",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 5,
    name: "onePlus",
    image: "/onePlus/oneplus5.jpg",
    internal: "128 GB",
    price: "76,999",
    company: "OnePlus",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 6,
    name: "onePlus",
    image: "/onePlus/oneplus6.jpg",
    internal: "128 GB",
    price: "96,999",
    company: "OnePlus",
    color: "green",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 7,
    name: "onePlus",
    image: "/onePlus/oneplus7.jpg",
    internal: "128 GB",
    price: "45,999",
    company: "OnePlus",
    color: "black",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 8,
    name: "onePlus",
    image: "/onePlus/oneplus8.jpg",
    internal: "128 GB",
    price: "67,999",
    company: "OnePlus",
    color: "white",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 9,
    name: "onePlus",
    image: "/onePlus/oneplus9.webp",
    internal: "128 GB",
    price: "96,999",
    company: "OnePlus",
    color: "black",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 10,
    name: "onePlus",
    image: "/onePlus/oneplus10.jpg",
    internal: "128 GB",
    price: "76,999",
    company: "OnePlus",
    color: "green",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 11,
    name: "onePlus",
    image: "/onePlus/oneplus11.jpg",
    internal: "128 GB",
    price: "89,999",
    company: "OnePlus",
    color: "black",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 12,
    name: "onePlus",
    image: "/onePlus/oneplus12.jpg",
    internal: "128 GB",
    price: "35,999",
    company: "OnePlus",
    color: "green",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 13,
    name: "onePlus",
    image: "/onePlus/oneplus13.jpg",
    internal: "128 GB",
    price: "48,999",
    company: "OnePlus",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 14,
    name: "onePlus",
    image: "/onePlus/oneplus14.webp",
    internal: "128 GB",
    price: "56,999",
    company: "OnePlus",
    color: "white",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 15,
    name: "onePlus",
    image: "/onePlus/oneplus15.jpg",
    internal: "128 GB",
    price: "45,999",
    company: "OnePlus",
    color: "black",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 16,
    name: "onePlus",
    image: "/onePlus/oneplus16.png",
    internal: "128 GB",
    price: "78,999",
    company: "OnePlus",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 17,
    name: "onePlus",
    image: "/onePlus/oneplus17.webp",
    internal: "128 GB",
    price: "32,999",
    company: "OnePlus",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 18,
    name: "onePlus",
    image: "/onePlus/oneplus18.jpg",
    internal: "128 GB",
    price: "48,999",
    company: "OnePlus",
    color: "green",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 19,
    name: "onePlus",
    image: "/onePlus/oneplus19.webp",
    internal: "128 GB",
    price: "38,999",
    company: "OnePlus",
    color: "black",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 20,
    name: "onePlus",
    image: "/onePlus/oneplus20.jpg",
    internal: "128 GB",
    price: "79,999",
    company: "OnePlus",
    color: "black",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 21,
    name: "onePlus",
    image: "/onePlus/oneplus21.png",
    internal: "128 GB",
    price: "43,999",
    company: "OnePlus",
    color: "white",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 22,
    name: "onePlus",
    image: "/onePlus/oneplus22.png",
    internal: "128 GB",
    price: "98,999",
    company: "OnePlus",
    color: "red",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 23,
    name: "onePlus",
    image: "/onePlus/oneplus23.png",
    internal: "128 GB",
    price: "34,999",
    company: "OnePlus",
    color: "green",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 24,
    name: "onePlus",
    image: "/onePlus/oneplus24.webp",
    internal: "128 GB",
    price: "56,999",
    company: "OnePlus",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 25,
    name: "onePlus",
    image: "/onePlus/oneplus25.png",
    internal: "128 GB",
    price: "67,999",
    company: "OnePlus",
    color: "black",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 26,
    name: "onePlus",
    image: "/onePlus/oneplus26.png",
    internal: "128 GB",
    price: "89,999",
    company: "OnePlus",
    color: "red",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 27,
    name: "onePlus",
    image: "/onePlus/oneplus27.png",
    internal: "128 GB",
    price: "76,999",
    company: "OnePlus",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 28,
    name: "onePlus",
    image: "/onePlus/oneplus28.png",
    name: "OnePlus",

    internal: "128 GB",
    price: "79,999",
    company: "OnePlus",
    color: "black",
    description: "1 year warrenty for phone",
  },
  {
    id: 29,
    name: "onePlus",
    image: "/onePlus/oneplus29.png",
    internal: "128 GB",
    price: "45,999",
    company: "OnePlus",
    color: "red",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
  {
    id: 30,
    name: "onePlus",
    image: "/onePlus/oneplus30.jpg",
    internal: "128 GB",
    price: "99,999",
    company: "OnePlus",
    color: "blue",
    description: "1 year warrenty for phone",
    name: "OnePlus",
  },
];
