export const PantsData = [
  {
    id: 1,
    image: "/pantsMen/pant1.webp",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1789",
    pastPrice: "1289",
    offer: "72% off",
    color: "black",
    name: "Pants",
  },
  {
    id: 2,
    image: "/pantsMen/pant26.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "489",
    pastPrice: "1289",
    offer: "45% off",
    color: "white",
    name: "Pants",
  },
  {
    id: 3,
    image: "/pantsMen/pant3.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "399",
    pastPrice: "999",
    offer: "65% off",
    color: "red",
    name: "Pants",
  },
  {
    id: 4,
    image: "/pantsMen/pant4.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "599",
    pastPrice: "1289",
    offer: "75% off",
    color: "green",
    name: "Pants",
  },
  {
    id: 5,
    image: "/pantsMen/pant5.webp",
    company: "Pants",
    description: "Men Regular Fit",
    price: "679",
    pastPrice: "1289",
    offer: "67% off",
    color: "blue",
    name: "Pants",
  },
  {
    id: 6,
    image: "/pantsMen/pant6.webp",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1599",
    pastPrice: "2999",
    offer: "55% off",
    color: "black",
    name: "Pants",
  },
  {
    id: 7,
    image: "/pantsMen/pant7.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1399",
    pastPrice: "1999",
    offer: "45% off",
    color: "white",
    name: "Pants",
  },
  {
    id: 8,
    image: "/pantsMen/pant8.avif",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1789",
    pastPrice: "2999",
    offer: "45% off",
    color: "green",
    name: "Pants",
  },
  {
    id: 9,
    image: "/pantsMen/pant9.webp",
    company: "Pants",
    description: "Men Regular Fit",
    price: "349",
    pastPrice: "1289",
    offer: "45% off",
    color: "black",
    name: "Pants",
  },
  {
    id: 10,
    image: "/pantsMen/pant10.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "569",
    pastPrice: "1289",
    offer: "75% off",
    color: "blue",
    name: "Pants",
  },
  {
    id: 11,
    image: "/pantsMen/pant11.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "349",
    pastPrice: "1289",
    offer: "56% off",
    color: "green",
    name: "Pants",
  },
  {
    id: 12,
    image: "/pantsMen/pant12.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "349",
    pastPrice: "1289",
    offer: "56% off",
    color: "green",
    name: "Pants",
  },
  {
    id: 13,
    image: "/pantsMen/pant13.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1599",
    pastPrice: "1989",
    offer: "66% off",
    color: "blue",
    name: "Pants",
  },
  {
    id: 14,
    image: "/pantsMen/pant14.webp",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1899",
    pastPrice: "2999",
    offer: "56% off",
    color: "red",
    name: "Pants",
  },
  {
    id: 15,
    image: "/pantsMen/pant15.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1349",
    pastPrice: "1999",
    offer: "56% off",
    color: "blue",
    name: "Pants",
  },
  {
    id: 16,
    image: "/pantsMen/pant16.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "459",
    pastPrice: "1289",
    offer: "56% off",
    color: "white",
    name: "Pants",
  },
  {
    id: 17,
    image: "/pantsMen/pant17.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "349",
    pastPrice: "999",
    offer: "56% off",
    color: "black",
    name: "Pants",
  },
  {
    id: 18,
    image: "/pantsMen/pant18.avif",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1349",
    pastPrice: "1999",
    offer: "66% off",
    color: "red",
    name: "Pants",
  },
  {
    id: 19,
    image: "/pantsMen/pant19.avif",
    company: "Pants",
    description: "Men Regular Fit",
    price: "849",
    pastPrice: "1289",
    offer: "56% off",
    color: "blue",
    name: "Pants",
  },
  {
    id: 20,
    image: "/pantsMen/pant20.webp",
    company: "Pants",
    description: "Men Regular Fit",
    price: "459",
    pastPrice: "1289",
    offer: "56% off",
    color: "white",
    name: "Pants",
  },
  {
    id: 21,
    image: "/pantsMen/pant21.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "599",
    pastPrice: "1289",
    offer: "65% off",
    color: "black",
    name: "Pants",
  },
  {
    id: 22,
    image: "/pantsMen/pant22.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1899",
    pastPrice: "2999",
    offer: "76% off",
    color: "green",
    name: "Pants",
  },
  {
    id: 23,
    image: "/pantsMen/pant23.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1399",
    pastPrice: "1999",
    offer: "56% off",
    color: "blue",
    name: "Pants",
  },
  {
    id: 24,
    image: "/pantsMen/pant24.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "899",
    pastPrice: "1289",
    offer: "45% off",
    color: "blue",
    name: "Pants",
  },
  {
    id: 25,
    image: "/pantsMen/pant27.jpg",
    company: "Pants",
    description: "Men Regular Fit",
    price: "1499",
    pastPrice: "1999",
    offer: "56% off",
    color: "white",
    name: "Pants",
  },
];
