export const SandolsData = [
  {
    id: 1,
    image: "/sandols/sandols1.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "399",
    pastPrice: "799",
    offer: "65% off",
    color: "black",
    name: "Sandols",
  },
  {
    id: 2,
    image: "/sandols/sandols2.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "599",
    pastPrice: "899",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
  {
    id: 3,
    image: "/sandols/sandols3.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "899",
    pastPrice: "1299",
    offer: "65% off",
    color: "green",
    name: "Sandols",
  },
  {
    id: 4,
    image: "/sandols/sandols4.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1299",
    pastPrice: "1599",
    offer: "65% off",
    color: "blue",
    name: "Sandols",
  },
  {
    id: 5,
    image: "/sandols/sandols5.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "599",
    pastPrice: "999",
    offer: "65% off",
    color: "black",
    name: "Sandols",
  },
  {
    id: 6,
    image: "/sandols/sandols6.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1399",
    pastPrice: "1599",
    offer: "65% off",
    color: "green",
    name: "Sandols",
  },
  {
    id: 7,
    image: "/sandols/sandols7.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "459",
    pastPrice: "799",
    offer: "65% off",
    color: "blue",
    name: "Sandols",
  },
  {
    id: 8,
    image: "/sandols/sandols8.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "679",
    pastPrice: "999",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
  {
    id: 9,
    image: "/sandols/sandols9.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,599",
    pastPrice: "1,999",
    offer: "65% off",
    color: "black",
    name: "Sandols",
  },
  {
    id: 10,
    image: "/sandols/sandols10.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "349",
    pastPrice: "599",
    offer: "65% off",
    color: "blue",
    name: "Sandols",
  },
  {
    id: 11,
    image: "/sandols/sandols11.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,799",
    pastPrice: "1,999",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
  {
    id: 12,
    image: "/sandols/sandols12.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,399",
    pastPrice: "1,599",
    offer: "65% off",
    color: "green",
    name: "Sandols",
  },
  {
    id: 13,
    image: "/sandols/sandols13.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,899",
    pastPrice: "2,499",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
  {
    id: 14,
    image: "/sandols/sandols14.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,699",
    pastPrice: "1,899",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
  {
    id: 15,
    image: "/sandols/sandols15.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,199",
    pastPrice: "1,399",
    offer: "65% off",
    color: "black",
    name: "Sandols",
  },
  {
    id: 16,
    image: "/sandols/sandols16.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "499",
    pastPrice: "999",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
  {
    id: 17,
    image: "/sandols/sandols17.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,499",
    pastPrice: "1,799",
    offer: "65% off",
    color: "green",
    name: "Sandols",
  },
  {
    id: 18,
    image: "/sandols/sandols18.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "899",
    pastPrice: "1,299",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
  {
    id: 19,
    image: "/sandols/sandols19.webp",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,299",
    pastPrice: "1,499",
    offer: "65% off",
    color: "blue",
    name: "Sandols",
  },
  {
    id: 20,
    image: "/sandols/sandols20.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "759",
    pastPrice: "999",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
  {
    id: 21,
    image: "/sandols/sandols21.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "399",
    pastPrice: "799",
    offer: "65% off",
    color: "blue",
    name: "Sandols",
  },
  {
    id: 22,
    image: "/sandols/sandols22.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,599",
    pastPrice: "1,999",
    offer: "65% off",
    color: "green",
    name: "Sandols",
  },
  {
    id: 23,
    image: "/sandols/sandols23.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,299",
    pastPrice: "1,499",
    offer: "65% off",
    color: "black",
    name: "Sandols",
  },
  {
    id: 24,
    image: "/sandols/sandols24.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "359",
    pastPrice: "599",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
  {
    id: 25,
    image: "/sandols/sandols25.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,299",
    pastPrice: "1,799",
    offer: "65% off",
    color: "green",
    name: "Sandols",
  },
  {
    id: 26,
    image: "/sandols/sandols26.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "699",
    pastPrice: "999",
    offer: "65% off",
    color: "blue",
    name: "Sandols",
  },
  {
    id: 27,
    image: "/sandols/sandols31.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,699",
    pastPrice: "1,999",
    offer: "65% off",
    color: "black",
    name: "Sandols",
  },
  {
    id: 28,
    image: "/sandols/sandols28.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "1,399",
    pastPrice: "1,599",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
  {
    id: 29,
    image: "/sandols/sandols29.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "459",
    pastPrice: "699",
    offer: "65% off",
    color: "green",
    name: "Sandols",
  },
  {
    id: 30,
    image: "/sandols/sandols30.jpg",
    company: "Sandols",
    description: "Men Regular Fit",
    price: "399",
    pastPrice: "799",
    offer: "65% off",
    color: "red",
    name: "Sandols",
  },
];
