export const Shoueses = [
  {
    id: 1,
    image: "/shouses/shouse1.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "599",
    pastPrice: "999",
    offer: "86% off",
    color: "black",
    name: "Shoes",
  },
  {
    id: 2,
    image: "/shouses/shouse2.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "1399",
    pastPrice: "2599",
    offer: "56% off",
    color: "white",
    name: "Shoes",
  },
  {
    id: 3,
    image: "/shouses/shouse3.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "399",
    pastPrice: "599",
    offer: "45% off",
    color: "red",
    name: "Shoes",
  },
  {
    id: 4,
    image: "/shouses/shouse4.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "899",
    pastPrice: "1999",
    offer: "45% off",
    color: "blue",
    name: "Shoes",
  },
  {
    id: 5,
    image: "/shouses/shouse5.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "799",
    pastPrice: "1499",
    offer: "67% off",
    color: "red",
    name: "Shoes",
  },
  {
    id: 6,
    image: "/shouses/shouse6.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "699",
    pastPrice: "1599",
    offer: "54% off",
    color: "black",
    name: "Shoes",
  },
  {
    id: 7,
    image: "/shouses/shouse7.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "1899",
    pastPrice: "2599",
    offer: "76% off",
    color: "green",
    name: "Shoes",
  },
  {
    id: 8,
    image: "/shouses/shouse8.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "1199",
    pastPrice: "2599",
    offer: "76% off",
    color: "blue",
    name: "Shoes",
  },
  {
    id: 9,
    image: "/shouses/shouse9.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "999",
    pastPrice: "2599",
    offer: "72% off",
    color: "red",
    name: "Shoes",
  },
  {
    id: 10,
    image: "/shouses/shouse10.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "1399",
    pastPrice: "1999",
    offer: "56% off",
    color: "green",
    name: "Shoes",
  },
  {
    id: 11,
    image: "/shouses/shouse11.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "1999",
    pastPrice: "2599",
    offer: "76% off",
    color: "black",
    name: "Shoes",
  },
  {
    id: 12,
    image: "/shouses/shouse12.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "679",
    pastPrice: "999",
    offer: "67% off",
    color: "white",
    name: "Shoes",
  },
  {
    id: 13,
    image: "/shouses/shouse13.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "499",
    pastPrice: "1999",
    offer: "67% off",
    color: "black",
    name: "Shoes",
  },
  {
    id: 14,
    image: "/shouses/shouse14.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "899",
    pastPrice: "1999",
    offer: "57% off",
    color: "blue",
    name: "Shoes",
  },
  {
    id: 15,
    image: "/shouses/shouse15.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "1299",
    pastPrice: "1599",
    offer: "57% off",
    color: "green",
    name: "Shoes",
  },
  {
    id: 16,
    image: "/shouses/shouse16.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "1499",
    pastPrice: "1999",
    offer: "45% off",
    color: "red",
    name: "Shoes",
  },
  {
    id: 17,
    image: "/shouses/shouse17.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "299",
    pastPrice: "999",
    offer: "47% off",
    color: "black",
    name: "Shoes",
  },
  {
    id: 18,
    image: "/shouses/shouse18.webp",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "1799",
    pastPrice: "2599",
    offer: "68% off",
    color: "white",
    name: "Shoes",
  },
  {
    id: 19,
    image: "/shouses/shouse19.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "1499",
    pastPrice: "1999",
    offer: "56% off",
    color: "green",
    name: "Shoes",
  },
  {
    id: 20,
    image: "/shouses/shouse20.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "999",
    pastPrice: "1999",
    offer: "56% off",
    color: "black",
    name: "Shoes",
  },
  {
    id: 21,
    image: "/shouses/shouse21.webp",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "599",
    pastPrice: "1699",
    offer: "67% off",
    color: "red",
    name: "Shoes",
  },
  {
    id: 22,
    image: "/shouses/shouse22.webp",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "699",
    pastPrice: "1000",
    offer: "67% off",
    color: "blue",
    name: "Shoes",
  },
  {
    id: 23,
    image: "/shouses/shouse23.webp",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "699",
    pastPrice: "1000",
    offer: "67% off",
    color: "blue",
    name: "Shoes",
  },
  {
    id: 24,
    image: "/shouses/shouse24.webp",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "699",
    pastPrice: "1000",
    offer: "67% off",
    color: "blue",
    name: "Shoes",
  },
  {
    id: 25,
    image: "/shouses/shouse25.webp",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "599",
    pastPrice: "1599",
    offer: "67% off",
    color: "black",
    name: "Shoes",
  },
  {
    id: 26,
    image: "/shouses/shouse26.webp",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "699",
    pastPrice: "1899",
    offer: "67% off",
    color: "white",
    name: "Shoes",
  },
  {
    id: 27,
    image: "/shouses/shouse27.jpg",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "499",
    pastPrice: "1699",
    offer: "67% off",
    color: "green",
    name: "Shoes",
  },
  {
    id: 28,
    image: "/shouses/shouse28.avif",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "399",
    pastPrice: "1399",
    offer: "67% off",
    color: "red",
    name: "Shoes",
  },
  {
    id: 29,
    image: "/shouses/shouse29.webp",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "599",
    pastPrice: "1999",
    offer: "67% off",
    color: "black",
    name: "Shoes",
  },
  {
    id: 30,
    image: "/shouses/shouse30.webp",
    company: "Shouse",
    description: "Regular Fit For Casual",
    price: "799",
    pastPrice: "1299",
    offer: "67% off",
    color: "green",
    name: "Shoes",
  },
];
