export const T_Shirt = [
  {
    id: 1,
    image: "/manTshirts/tshirt1.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1789",
    pastPrice: "1289",
    offer: "72% off",
    color: "black",
    name: "Tshrts",
  },
  {
    id: 2,
    image: "/manTshirts/tshirt2.jpeg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "489",
    pastPrice: "1289",
    offer: "45% off",
    color: "white",
    name: "Tshrts",
  },
  {
    id: 3,
    image: "/manTshirts/tshirt3.webp",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "399",
    pastPrice: "999",
    offer: "65% off",
    color: "red",
    name: "Tshrts",
  },
  {
    id: 4,
    image: "/manTshirts/tshirt32.png",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "599",
    pastPrice: "1289",
    offer: "75% off",
    color: "green",
    name: "Tshrts",
  },
  {
    id: 5,
    image: "/manTshirts/tshirt5.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "679",
    pastPrice: "1289",
    offer: "67% off",
    color: "blue",
    name: "Tshrts",
  },

  {
    id: 6,
    image: "/manTshirts/tshirt6.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1599",
    pastPrice: "2999",
    offer: "55% off",
    color: "black",
    name: "Tshrts",
  },
  {
    id: 7,
    image: "/manTshirts/tshirt7.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1399",
    pastPrice: "1999",
    offer: "45% off",
    color: "white",
    name: "Tshrts",
  },
  {
    id: 8,
    image: "/manTshirts/tshirt8.jpeg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1789",
    pastPrice: "2999",
    offer: "45% off",
    color: "green",
    name: "Tshrts",
  },
  {
    id: 9,
    image: "/manTshirts/tshirt9.webp",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "349",
    pastPrice: "1289",
    offer: "45% off",
    color: "black",
    name: "Tshrts",
  },
  {
    id: 10,
    image: "/manTshirts/tshirt10.webp",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "569",
    pastPrice: "1289",
    offer: "75% off",
    color: "blue",
    name: "Tshrts",
  },
  {
    id: 11,
    image: "/manTshirts/tshirt11.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "349",
    pastPrice: "1289",
    offer: "56% off",
    color: "green",
    name: "Tshrts",
  },
  {
    id: 12,
    image: "/manTshirts/tshirt31.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "899",
    pastPrice: "1289",
    offer: "59% off",
    color: "red",
    name: "Tshrts",
  },
  {
    id: 13,
    image: "/manTshirts/tshirt13.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1599",
    pastPrice: "1989",
    offer: "66% off",
    color: "blue",
    name: "Tshrts",
  },
  {
    id: 14,
    image: "/manTshirts/tshirt14.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1899",
    pastPrice: "2999",
    offer: "56% off",
    color: "red",
    name: "Tshrts",
  },
  {
    id: 15,
    image: "/manTshirts/tshirt15.webp",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1349",
    pastPrice: "1999",
    offer: "56% off",
    color: "blue",
    name: "Tshrts",
  },
  {
    id: 16,
    image: "/manTshirts/tshirt16.jpeg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "459",
    pastPrice: "1289",
    offer: "56% off",
    color: "white",
    name: "Tshrts",
  },
  {
    id: 17,
    image: "/manTshirts/tshirt17.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "349",
    pastPrice: "999",
    offer: "56% off",
    color: "black",
    name: "Tshrts",
  },
  {
    id: 18,
    image: "/manTshirts/tshirt18.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1349",
    pastPrice: "1999",
    offer: "66% off",
    color: "red",
    name: "Tshrts",
  },
  {
    id: 19,
    image: "/manTshirts/tshirt19.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "849",
    pastPrice: "1289",
    offer: "56% off",
    color: "blue",
    name: "Tshrts",
  },
  {
    id: 20,
    image: "/manTshirts/tshirt20.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "459",
    pastPrice: "1289",
    offer: "56% off",
    color: "white",
    name: "Tshrts",
  },
  {
    id: 21,
    image: "/manTshirts/tshirt21.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "599",
    pastPrice: "1289",
    offer: "65% off",
    color: "black",
    name: "Tshrts",
  },
  {
    id: 22,
    image: "/manTshirts/tshirt22.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1899",
    pastPrice: "2999",
    offer: "76% off",
    color: "green",
    name: "Tshrts",
  },
  {
    id: 23,
    image: "/manTshirts/tshirt23.png",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1399",
    pastPrice: "1999",
    offer: "56% off",
    color: "blue",
    name: "Tshrts",
  },
  {
    id: 24,
    image: "/manTshirts/tshirt24.webp",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "899",
    pastPrice: "1289",
    offer: "45% off",
    color: "blue",
    name: "Tshrts",
  },
  {
    id: 25,
    image: "/manTshirts/tshirt25.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1499",
    pastPrice: "1999",
    offer: "56% off",
    color: "white",
    name: "Tshrts",
  },
  {
    id: 26,
    image: "/manTshirts/tshirt26.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1799",
    pastPrice: "2999",
    offer: "45% off",
    color: "black",
    name: "Tshrts",
  },
  {
    id: 27,
    image: "/manTshirts/tshirt27.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "789",
    pastPrice: "1999",
    offer: "56% off",
    color: "red",
    name: "Tshrts",
  },
  {
    id: 28,
    image: "/manTshirts/tshirt28.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1999",
    pastPrice: "2999",
    offer: "56% off",
    color: "green",
    name: "Tshrts",
  },
  {
    id: 29,
    image: "/manTshirts/tshirt29.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "1699",
    pastPrice: "2489",
    offer: "56% off",
    color: "black",
    name: "Tshrts",
  },
  {
    id: 30,
    image: "/manTshirts/tshirt30.jpg",
    company: "Tshirt",
    description: "Men Regular Fit",
    price: "459",
    pastPrice: "1289",
    offer: "56% off",
    color: "blue",
    name: "Tshrts",
  },
];
