export const WatchesData = [
  {
    id: 1,
    image: "/watches/watches1.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "599",
    pastPrice: "999",
    offer: "76% off",
    color: "red",
    name: "Watches",
  },
  {
    id: 2,
    image: "/watches/watches2.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "2,999",
    pastPrice: "5,999",
    offer: "66% off",
    color: "black",
    name: "Watches",
  },
  {
    id: 3,
    image: "/watches/watches3.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "899",
    pastPrice: "1,999",
    offer: "76% off",
    color: "green",
    name: "Watches",
  },
  {
    id: 4,
    image: "/watches/watches4.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "5,999",
    pastPrice: "6,999",
    offer: "76% off",
    color: "blue",
    name: "Watches",
  },
  {
    id: 5,
    image: "/watches/watches5.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "3,999",
    pastPrice: "4,999",
    offer: "76% off",
    color: "white",
    name: "Watches",
  },
  {
    id: 6,
    image: "/watches/watches6.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "2,999",
    pastPrice: "4,999",
    offer: "76% off",
    color: "black",
    name: "Watches",
  },
  {
    id: 7,
    image: "/watches/watches7.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "8,999",
    pastPrice: "9,999",
    offer: "76% off",
    color: "red",
    name: "Watches",
  },
  {
    id: 8,
    image: "/watches/watches8.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "1,999",
    pastPrice: "2,999",
    offer: "76% off",
    color: "green",
    name: "Watches",
  },
  {
    id: 9,
    image: "/watches/watches9.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "5,999",
    pastPrice: "6,999",
    offer: "76% off",
    color: "blue",
    name: "Watches",
  },
  {
    id: 10,
    image: "/watches/watches10.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "3,999",
    pastPrice: "4,999",
    offer: "76% off",
    color: "black",
    name: "Watches",
  },
  {
    id: 11,
    image: "/watches/watches11.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "7,999",
    pastPrice: "9,999",
    offer: "76% off",
    color: "white",
    name: "Watches",
  },
  {
    id: 12,
    image: "/watches/watches12.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "1,999",
    pastPrice: "2,999",
    offer: "76% off",
    color: "green",
    name: "Watches",
  },
  {
    id: 13,
    image: "/watches/watches13.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "6,999",
    pastPrice: "8,999",
    offer: "76% off",
    color: "red",
    name: "Watches",
  },
  {
    id: 14,
    image: "/watches/watches14.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "7,999",
    pastPrice: "9,999",
    offer: "76% off",
    color: "white",
    name: "Watches",
  },
  {
    id: 15,
    image: "/watches/watches15.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "2,999",
    pastPrice: "5,999",
    offer: "76% off",
    color: "blue",
    name: "Watches",
  },
  {
    id: 16,
    image: "/watches/watches16.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "3,999",
    pastPrice: "5,999",
    offer: "76% off",
    color: "green",
    name: "Watches",
  },
  {
    id: 17,
    image: "/watches/watches17.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "2,999",
    pastPrice: "3,999",
    offer: "76% off",
    color: "white",
    name: "Watches",
  },
  {
    id: 18,
    image: "/watches/watches31.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "1,999",
    pastPrice: "2,999",
    offer: "76% off",
    color: "black",
    name: "Watches",
  },
  {
    id: 19,
    image: "/watches/watches19.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "2,999",
    pastPrice: "4,999",
    offer: "76% off",
    color: "red",
    name: "Watches",
  },
  {
    id: 20,
    image: "/watches/watches20.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "999",
    pastPrice: "1,999",
    offer: "76% off",
    color: "green",
    name: "Watches",
  },
  {
    id: 21,
    image: "/watches/watches21.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "599",
    pastPrice: "1,999",
    offer: "76% off",
    color: "white",
    name: "Watches",
  },
  {
    id: 22,
    image: "/watches/watches34.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "999",
    pastPrice: "2,999",
    offer: "76% off",
    color: "black",
    name: "Watches",
  },
  {
    id: 23,
    image: "/watches/watches23.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "999",
    pastPrice: "1,999",
    offer: "76% off",
    color: "red",
    name: "Watches",
  },
  {
    id: 24,
    image: "/watches/watches24.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "7,999",
    pastPrice: "9,999",
    offer: "76% off",
    color: "green",
    name: "Watches",
  },
  {
    id: 25,
    image: "/watches/watches25.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "2,999",
    pastPrice: "3,999",
    offer: "76% off",
    color: "blue",
    name: "Watches",
  },
  {
    id: 26,
    image: "/watches/watches26.webp",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "2,999",
    pastPrice: "3,999",
    offer: "76% off",
    color: "white",
    name: "Watches",
  },
  {
    id: 27,
    image: "/watches/watches27.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "699",
    pastPrice: "999",
    offer: "76% off",
    color: "green",
    name: "Watches",
  },
  {
    id: 28,
    image: "/watches/watches28.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "659",
    pastPrice: "999",
    offer: "76% off",
    color: "blue",
    name: "Watches",
  },
  {
    id: 29,
    image: "/watches/watches29.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "7,999",
    pastPrice: "9,999",
    offer: "76% off",
    color: "red",
    name: "Watches",
  },
  {
    id: 30,
    image: "/watches/watches30.jpg",
    company: "Watch",
    description: "1 Year garrenty for Watch",
    price: "2,999",
    pastPrice: "3,999",
    offer: "76% off",
    color: "black",
    name: "Watches",
  },
];
